version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kitchensink-app
    container_name: kitchensink-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/kitchensink
      SERVER_PORT: 8080
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: kitchensink
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
