management:
  endpoints:
    web:
      exposure:
        include: info,health
info:
  app:
    version: '@project.version@'
phone:
  validation:
    enabled: false
spring:
  application:
    name: kitchensink
  data:
    mongodb:
      database: ${SPRING_DATA_MONGODB_DATABASE:kitchensink}
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}