name: Generate JUnit Tests v2

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened]

permissions:
  contents: write  # allow pushing commits back
  pull-requests: write

jobs:
  generate-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Fetch origin/main
        run: git fetch origin main

      - name: Grant execute permissions to script
        run: chmod +x scripts/generate-tests.sh

      - name: Show changed files
        run: git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}

      - name: Run test generator script
        run: ./scripts/generate-tests.sh
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit generated tests
        run: |
          git config user.name "CI Bot"
          git config user.email "ci@member.com"
          git add src/test/java/generated
          # Only commit if there are changes
          git commit -m "Add AI-generated unit tests"
          git push
