name: Generate JUnit Tests v2

on:
  pull_request: # Trigger on pull request events
    types: [opened, reopened] # Specifically when a PR is opened or reopened
    branches:
      - main # Target branch for the pull request
    paths: # Add this section to filter by file paths
      - 'src/main/java/**/*.java' # Only trigger if Java files in src/main/java are changed

permissions:
  contents: write # Allow the action to write to the repository
  pull-requests: write # Allow the action to create and update pull requests

jobs:
  generate-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          # fetch-depth: ${{ steps.base-depth.outputs.base-depth }}
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - name: Fetch origin/main
        run: git fetch origin main
      - name: Grant execute permissions to script
        run: chmod +x scripts/generate-tests.sh
      - name: Show changed files
        run: git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
      - name: Run test generator script
        run: ./scripts/generate-tests.sh ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_PRJ: ${{ secrets.OPENAI_PRJ }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
      - name: Commit generated tests
        run: |
          git config user.name "CI Bot"
          git config user.email "ci@member.com"
          git add src/test/java
          git commit -m "Add AI-generated unit tests"
          git push
          
